# Generated by Django 5.2.1 on 2026-05-19 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_actions', '0001_initial'),
        ('parcels', '0014_remove_parcel_parcel_geom_updated_at_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaction',
            options={'ordering': ['status', 'due_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='clientaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='clientaction',
            index=models.Index(fields=['parcel', 'status'], name='client_acti_parcel__c2fb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaction',
            index=models.Index(fields=['status', 'due_date'], name='client_acti_status_9fc103_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaction',
            index=models.Index(fields=['created_at'], name='client_acti_created_61e3e5_idx'),
        ),
    ]
