# Generated by Django 5.1.6 on 2026-05-19 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0014_remove_parcel_parcel_geom_updated_at_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(default='Intervention terrain', max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('in_progress', 'En cours'), ('done', 'Réalisée'), ('cancelled', 'Annulée'), ('blocked', 'Bloquée')], db_index=True, default='scheduled', max_length=20)),
                ('report', models.TextField(blank=True)),
                ('visible_to_client', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_interventions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_field_interventions', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_interventions', to='parcels.parcel')),
            ],
            options={
                'ordering': ['-scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['parcel', 'status'], name='field_inter_parcel__5c3f96_idx'), models.Index(fields=['scheduled_date', 'status'], name='field_inter_schedul_fb6c86_idx'), models.Index(fields=['visible_to_client', 'status'], name='field_inter_visible_edb3f7_idx')],
            },
        ),
    ]
