# Generated by Django 5.1.6 on 2026-04-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_status_54bdfc_idx',
            old_name='organizatio_status_d8710f_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_organiz_91825f_idx',
            old_name='organizatio_organiz_eafab5_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='organizatio_organiz_c1d93c_idx',
            old_name='organizatio_organiz_26fc17_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='organizatio_user_id_494b92_idx',
            old_name='organizatio_user_id_1da8b7_idx',
        ),
    ]
