# Generated by Django 5.0.4 on 2026-05-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_geojson', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='geojsonlayer',
            new_name='client_geoj_client__ec844d_idx',
            old_name='client_geoj_client__1c0c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='geojsonlayer',
            new_name='client_geoj_client__3e400c_idx',
            old_name='client_geoj_client__f2ec25_idx',
        ),
        migrations.RenameIndex(
            model_name='geojsonlayer',
            new_name='client_geoj_created_a914d3_idx',
            old_name='client_geoj_created_bf7e5b_idx',
        ),
    ]
