# Generated by Django 5.0.4 on 2026-05-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_map_layers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientmaplayer',
            new_name='client_map__client__097a27_idx',
            old_name='client_map_client__active_idx',
        ),
        migrations.RenameIndex(
            model_name='clientmaplayer',
            new_name='client_map__client__c02f8c_idx',
            old_name='client_map_client__status_idx',
        ),
        migrations.RenameIndex(
            model_name='clientmaplayer',
            new_name='client_map__client__eb0a8c_idx',
            old_name='client_map_client__type_idx',
        ),
        migrations.RenameIndex(
            model_name='clientmaplayer',
            new_name='client_map__client__61210e_idx',
            old_name='client_map_client__format_idx',
        ),
        migrations.RenameIndex(
            model_name='clientmaplayer',
            new_name='client_map__created_67fbf1_idx',
            old_name='client_map_created_idx',
        ),
        migrations.AlterField(
            model_name='clientmaplayer',
            name='data_format',
            field=models.CharField(choices=[('geojson', 'GeoJSON'), ('geotiff', 'GeoTIFF'), ('cog', 'Cloud Optimized GeoTIFF'), ('mbtiles', 'MBTiles'), ('xyz', 'Tuiles XYZ'), ('wms', 'WMS'), ('wfs', 'WFS'), ('wmts', 'WMTS'), ('png', 'PNG'), ('jpg', 'JPEG'), ('other', 'Autre')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientmaplayer',
            name='layer_type',
            field=models.CharField(choices=[('geojson', 'GeoJSON'), ('orthophoto', 'Orthophoto'), ('drone_image', 'Image drone'), ('dem', 'MNT / DEM'), ('hillshade', 'Ombrage relief'), ('slope', 'Pente'), ('tiles', 'Tuiles XYZ'), ('wms', 'WMS'), ('wfs', 'WFS'), ('wmts', 'WMTS'), ('other', 'Autre')], db_index=True, max_length=50),
        ),
    ]
