# Generated by Django 5.2.1 on 2026-05-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_map_layers", "0005_remove_legacy_geojson_layers"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clientmaplayer",
            new_name="client_map__client__baf43c_idx",
            old_name="client_map__client__source__idx",
        ),
        migrations.RenameIndex(
            model_name="clientmaplayerfeature",
            new_name="client_map__layer_i_0edffc_idx",
            old_name="client_map__layer_i_idx",
        ),
        migrations.RenameIndex(
            model_name="clientmaplayerfeature",
            new_name="client_map__source__51d104_idx",
            old_name="client_map__source__idx",
        ),
    ]
