# Generated by Django 5.1.6 on 2026-04-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_postgis_organizations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parcel',
            new_name='parcels_par_owner_i_4b6958_idx',
            old_name='parcels_par_owner_i_1e7ff7_idx',
        ),
        migrations.RenameIndex(
            model_name='parcel',
            new_name='parcels_par_owner_i_6da9d0_idx',
            old_name='parcels_par_owner_i_6de4a2_idx',
        ),
        migrations.RenameIndex(
            model_name='parcel',
            new_name='parcels_par_organiz_88727e_idx',
            old_name='parcels_par_organiz_111111_idx',
        ),
        migrations.RenameIndex(
            model_name='parcel',
            new_name='parcels_par_organiz_9a1aaf_idx',
            old_name='parcels_par_organiz_222222_idx',
        ),
        migrations.RenameIndex(
            model_name='parcel',
            new_name='parcels_par_commune_f560f0_idx',
            old_name='parcels_par_commune_8ec4dd_idx',
        ),
    ]
