# Generated by Django 5.0.4 on 2026-04-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_sync_geom_fields_trigger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parcel',
            new_name='parcels_par_archive_c91dff_idx',
            old_name='parcels_par_archive_78c9e1_idx',
        ),
    ]
