# Generated by MAPGEO maintenance script

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0012_index_geometry_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="nicad",
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
