# Generated by Django 5.2.1 on 2026-05-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0013_parcel_nicad'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parcel',
            name='parcel_geom_updated_at_idx',
        ),
    ]
