# Generated by Django 5.1.6 on 2026-04-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importjob',
            new_name='imports_imp_status_717e0b_idx',
            old_name='imports_imp_status_1dd98f_idx',
        ),
        migrations.RenameIndex(
            model_name='importjob',
            new_name='imports_imp_created_d4d672_idx',
            old_name='imports_imp_created_4ff5b4_idx',
        ),
        migrations.RenameIndex(
            model_name='importrowresult',
            new_name='imports_imp_job_id_6829b7_idx',
            old_name='imports_imp_job_id_38365d_idx',
        ),
        migrations.RenameIndex(
            model_name='importrowresult',
            new_name='imports_imp_job_id_513229_idx',
            old_name='imports_imp_job_id_0a840f_idx',
        ),
    ]
