# Generated by Django 5.1.6 on 2026-05-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_private_import_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='file',
            field=models.FileField(upload_to='imports/%Y/%m/'),
        ),
    ]
