# Generated by Django 5.2.1 on 2026-05-11 13:43

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0004_alter_importjob_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="file",
            field=models.FileField(
                storage=config.storage.PrivateMediaStorage("imports"),
                upload_to=config.storage.private_import_upload_to,
            ),
        ),
    ]
