# Generated by Django 5.1.6 on 2026-04-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parceldocument',
            new_name='documents_p_parcel__d3e6f2_idx',
            old_name='documents_p_parcel__1fe53e_idx',
        ),
        migrations.RenameIndex(
            model_name='parceldocument',
            new_name='documents_p_parcel__116dac_idx',
            old_name='documents_p_parcel__1144bf_idx',
        ),
    ]
