# Generated by Django 5.0.4 on 2026-05-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_private_document_storage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parceldocument',
            new_name='documents_p_source_152700_idx',
            old_name='documents_p_source__a9c4f8_idx',
        ),
    ]
