# Generated by Django 5.1.6 on 2026-04-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportmessage',
            new_name='support_sup_ticket__8eea9f_idx',
            old_name='support_sup_ticket__0dd092_idx',
        ),
        migrations.RenameIndex(
            model_name='supportmessage',
            new_name='support_sup_author__1077f2_idx',
            old_name='support_sup_author__4ddb19_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_user_id_2e68d8_idx',
            old_name='support_sup_user_id_455176_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_status_eeda74_idx',
            old_name='support_sup_status__c121ae_idx',
        ),
    ]
