# Generated by Django 5.1.6 on 2026-04-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_rename_support_sup_ticket__0dd092_idx_support_sup_ticket__8eea9f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
