# Generated by Django 5.1.6 on 2026-05-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_private_attachment_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support/%Y/%m/'),
        ),
    ]
