# Generated by Django 5.2.1 on 2026-05-11 13:43

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0007_alter_supportmessage_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportmessage",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=config.storage.PrivateMediaStorage("support"),
                upload_to=config.storage.private_support_attachment_upload_to,
            ),
        ),
    ]
